From Yann Dirson  <dirson@debian.org>:         * util/mkbimage: Misc syntax fixes.

diff --git a/grub/util/mkbimage b/grub/util/mkbimage
--- a/grub/util/mkbimage
+++ b/grub/util/mkbimage
@@ -19,7 +19,7 @@
 # program's maintainer or write to: The Free Software Foundation,
 # Inc.; 59 Temple Place, Suite 330; Boston, MA 02111-1307, USA.
 
-# $Id: mkbimage,v 1.17 2003/08/09 12:19:43 tlaronde Exp $
+# $Id: mkbimage,v 1.18 2004/04/29 19:45:11 robertmh Exp $
 
 # Global variables
 tarfile=
@@ -58,7 +58,7 @@ stage2_os_name=
 
 # Name by which this script was invoked.
 program=`echo "$0" | sed -e 's/[^\/]*\///g'`
-version_number='$Revision: 1.17 $'
+version_number='$Revision: 1.18 $'
 
 usage="
 Usage: $program [-hVF] [-t TYPE] [-d DIRECTORY] [-s FS_TYPE] -f TAR_FILE
@@ -178,9 +178,12 @@ mkbimage_cp ()
   esac
 
   if [ "$offset" = 0 ] && which $cp > /dev/null ; then
-    $mkdir ${image}:/boot
-    $mkdir ${image}:/boot/grub
-    $cp ${image}1/boot/grub/* ${image}:/boot/grub/
+    for dir in $(cd ${image}1 && find -type d) ; do
+	$mkdir ${image}:$dir
+    done
+    for file in $(cd ${image}1 && find -type f) ; do
+	$cp ${image}1/$file ${image}:$file
+    done
   elif [ "`id -u`" = "0" ] ; then
     losetup $lo_options /dev/loop1 $image
     mkdir ${image}.mnt
@@ -345,7 +348,7 @@ if [ "$image_type" = "hd" ]; then
 
 
 EOT
-  offset="-o $(($sectors * $block_size))" 
+  offset="$(($sectors * $block_size))" 
   type_option=
 else
   offset="0"
@@ -355,7 +358,8 @@ fi
 mkbimage_mkfs
 
 # then untar the files
-mkdir ${image}1 2>/dev/null
+[ ! -e ${image}1 ] || { echo "${image}1 exists, please remove it first"; exit 1;}
+mkdir -p ${image}1
 $decompress $tarfile | tar -C ${image}1 $debug -xf -
 
 # copy the untarred files into the filesystem image
@@ -364,7 +368,7 @@ mkbimage_cp
 #We verify that the stage2 exists and we search the name
 stage2_os_name=`find ${image}1 -name stage2 -type f`
 
-[ ! $stage2_os_name ] && { echo "I can't find stage2!"; exit 1;}
+[ -r "$stage2_os_name" ] || { echo "I can't find stage2!"; exit 1;}
 
 #------------------------- GRUB stuff
 if [ "$image_type" = "hd" ]; then
@@ -407,5 +411,7 @@ mkisofs -b <image> -hard-disk-boot -c boot.catalog -o raw.iso <dir>
 
 Enjoy!
 EOF
+
+rm -rf ${image}1
 
 exit 0
